describe('resources', () => {
  it('lists all the resources in the menu', () => {
    cy.visit('/admin');
    cy.contains('Prerequis')
    cy.contains('Inscriptions')
    cy.contains('target types')
    cy.contains('Activite pedagogiques')
    cy.contains('Alternances')
    cy.contains('rules')
    cy.contains('Session de formations')
    cy.contains('Composition a choixes')
    cy.contains('Prefix declarations')
    cy.contains('Perimetre de recrutements')
    cy.contains('Coded properties')
    cy.contains('Concepts')
    cy.contains('Admissions')
    cy.contains('libraries')
    cy.contains('Hierarchical code lists')
    cy.contains('validators')
    cy.contains('Institutions')
    cy.contains('Certifications')
    cy.contains('update executables')
    cy.contains('constraints')
    cy.contains('Ordered collections')
    cy.contains('Session d informations')
    cy.contains('ask validators')
    cy.contains('Outcomes')
    cy.contains('Natural people')
    cy.contains('Criteria and methods')
    cy.contains('Parameters')
    cy.contains('Offre de formations')
    cy.contains('Niveau de certifications')
    cy.contains('Modules')
  });
});
